version: "3"
services:
  db:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=culturedb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local